apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-metrics
  namespace: kube-system
spec:
  rules:
  - host: k8s-metrics.art.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kube-state-metrics
            port:
              number: 8080
