apiVersion: v1
kind: ConfigMap
metadata:
  name: tv-mysql-configmap
data:
  docker.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
    max_connect_errors=10000
    max_connections=1000
    join_buffer_size=512M
    key_buffer_size=256M